web server add

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,15 +1,90 @@
 #!/usr/bin/env bash
-#redirection
-sudo apt-get update
-sudo apt-get install -y nginx
+# Deploy a new web server with Nginx
 
-echo "Hello World!" | sudo tee /var/www/html/index.nginx-debaian.html
-replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
-sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default
+# Uncomment to see the script run in action
+# set -x
 
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/c_404.html
-new_replace="listen 80 default_server;\n\terror_page 404 \/c_404.html;\n\tlocation = \/c_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
-sudo sed -i "s/listen 80 default_server;/$new_replace/" /etc/nginx/sites-enabled/default
+echo -e "Updating and doing some minor checks...\n"
 
-sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
+function install() {
+    command -v "$1" &> /dev/null
+
+    if [ $? -ne 0 ]; then
+        echo -e "Installing: $1\n"
+        sudo apt-get update -y -qq && \
+            sudo apt-get install -y "$1" -qq
+        echo -e "\n"
+    else
+        echo -e "${1} is already installed.\n"
+    fi
+}
+
+install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# Allowing Nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+web_dir="/var/www"
+if [ -d "$web_dir" ]; then
+    sudo chown -R "$USER":"$USER" "$web_dir"
+    sudo chmod -R 755 "$web_dir"
+else
+    sudo mkdir -p "$web_dir"
+    sudo chown -R "$USER":"$USER" "$web_dir"
+    sudo chmod -R 755 "$web_dir"
+fi
+
+# Create directories if not present
+for dir in "$web_dir"/{html,error}; do
+    if ! [ -d "$dir" ]; then
+        mkdir -p "$dir"
+    fi
+done
+
+# Creating new index
+echo "Hello World!" > "$web_dir"/html/index.html
+
+# Create new error page
+echo "Ceci n'est pas une page" > "$web_dir"/html/error_404.html
+
+# Backup default server config file
+sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default_backup
+
+# Create a new server configuration file
+server_config=$(cat <<EOL
+server {
+    listen 80 default_server;
+    listen [::]:80 default_server;
+    root $web_dir/html;
+    index index.html index.htm index.nginx-debian.html;
+    server_name _;
+    add_header X-Served-By \$hostname;
+    location / {
+        try_files \$uri \$uri/ =404;
+    }
+    if (\$request_filename ~ redirect_me) {
+        rewrite ^ https://th3-gr00t.tk/ permanent;
+    }
+    error_page 404 /error_404.html;
+    location = /error_404.html {
+        internal;
+    }
+}
+EOL
+)
+
+# Create a new server config file
+sudo echo "$server_config" | sudo tee /etc/nginx/sites-available/web_server
+
+# Enable the new server config by creating a symlink
+sudo ln -s /etc/nginx/sites-available/web_server /etc/nginx/sites-enabled/
+
+# Test Nginx configuration
+sudo nginx -t
+
+# Restart Nginx
 sudo service nginx restart
+
